import { AppDataSource } from '../data-source';
import { Perfume } from '../entities/Perfume';

const perfumeData = [
  {
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    description: 'عطر رجالي خشبي أروماتيك منعش، مناسب للشغل والخروجات، بثبات جيد وفخامة واضحة.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
    tags: ['woody', 'fresh', 'citrus', 'aromatic'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 6500, stock: 8 }],
  },
  {
    name: 'Dior Sauvage',
    brand: 'Dior',
    description: 'عطر رجالي منعش وتوابلي، مشهور جدًا وسهل اللبس يوميًا، مناسب لمعظم الأوقات.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1619994403073-2cec1df8cc6e?auto=format&fit=crop&w=900&q=80',
    tags: ['spicy', 'fresh', 'amber', 'bergamot'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 6200, stock: 7 }],
  },
  {
    name: 'Acqua di Gio Profumo',
    brand: 'Giorgio Armani',
    description: 'عطر رجالي بحري مع لمسة بخور أنيقة، ممتاز للصيف والمناسبات الرسمية.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
    tags: ['aquatic', 'incense', 'fresh', 'marine'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 75, price: 5800, stock: 6 }],
  },
  {
    name: 'Y Eau de Parfum',
    brand: 'Yves Saint Laurent',
    description: 'عطر رجالي حديث ومنعش بحلاوة خفيفة، مناسب للشباب وللاستخدام اليومي.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=900&q=80',
    tags: ['aromatic', 'apple', 'woody', 'fresh'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5400, stock: 7 }],
  },
  {
    name: 'Terre d’Hermès',
    brand: 'Hermès',
    description: 'عطر رجالي حمضي خشبي أنيق جدًا، مناسب للذوق الهادئ والكلاسيك.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'woody', 'earthy', 'mineral'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 6900, stock: 5 }],
  },
  {
    name: '1 Million',
    brand: 'Paco Rabanne',
    description: 'عطر رجالي حلو وتوابلي، شبابي ومناسب للسهرات.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=900&q=80',
    tags: ['sweet', 'spicy', 'leather', 'amber'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 4700, stock: 8 }],
  },
  {
    name: 'Invictus',
    brand: 'Paco Rabanne',
    description: 'عطر رجالي منعش بحري، رياضي وشبابي ومناسب للصيف.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1610240644455-3edc55c375fe?auto=format&fit=crop&w=900&q=80',
    tags: ['aquatic', 'fresh', 'citrus', 'marine'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 4500, stock: 8 }],
  },
  {
    name: 'Le Male Le Parfum',
    brand: 'Jean Paul Gaultier',
    description: 'عطر رجالي دافئ جذاب بالفانيلا والهيل، مناسب جدًا للمساء.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
    tags: ['vanilla', 'cardamom', 'amber', 'warm'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 125, price: 5900, stock: 5 }],
  },
  {
    name: 'The One for Men',
    brand: 'Dolce & Gabbana',
    description: 'عطر رجالي أنيق بدفء تبغي وتوابلي، مناسب للخروجات والسهرات.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1619994403073-2cec1df8cc6e?auto=format&fit=crop&w=900&q=80',
    tags: ['tobacco', 'spicy', 'amber', 'warm'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5100, stock: 5 }],
  },
  {
    name: 'Stronger With You Absolutely',
    brand: 'Emporio Armani',
    description: 'عطر رجالي حلو ودافئ بثبات قوي، مناسب للأجواء الباردة.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
    tags: ['rum', 'vanilla', 'sweet', 'warm spicy'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 6100, stock: 5 }],
  },
  {
    name: 'Spicebomb Extreme',
    brand: 'Viktor & Rolf',
    description: 'عطر رجالي قوي وحار مع فانيلا وتبغ، مناسب للشتاء والسهرات.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=900&q=80',
    tags: ['spicy', 'vanilla', 'tobacco', 'warm'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 90, price: 5700, stock: 4 }],
  },
  {
    name: 'Azzaro Wanted by Night',
    brand: 'Azzaro',
    description: 'عطر رجالي حلو وتوابلي ملفت، مناسب جدًا للخروج الليلي.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=900&q=80',
    tags: ['cinnamon', 'sweet', 'woody', 'tobacco'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 4800, stock: 6 }],
  },
  {
    name: 'Prada Luna Rossa Carbon',
    brand: 'Prada',
    description: 'عطر رجالي حديث بلمسة معدنية صابونية نظيفة، عملي جدًا.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=900&q=80',
    tags: ['fresh', 'metallic', 'lavender', 'ambroxan'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5300, stock: 6 }],
  },
  {
    name: 'Valentino Uomo Born in Roma',
    brand: 'Valentino',
    description: 'عطر رجالي شبابي أنيق بلمسة معدنية وفانيلا خفيفة.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1610240644455-3edc55c375fe?auto=format&fit=crop&w=900&q=80',
    tags: ['violet leaf', 'mineral', 'vanilla', 'woody'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5600, stock: 5 }],
  },
  {
    name: 'Club de Nuit Intense Man',
    brand: 'Armaf',
    description: 'عطر رجالي مشهور بنفحة حمضية خشبية قوية، قيمة ممتازة مقابل السعر.',
    category: 'men',
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'smoky', 'woody', 'fresh'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 105, price: 2500, stock: 12 }],
  },

  {
    name: 'Chanel No. 5',
    brand: 'Chanel',
    description: 'عطر نسائي كلاسيكي فاخر، زهري وألدهايدي، مناسب للسهرات والذوق الراقي.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1615634262417-4e3f2a39c6f4?auto=format&fit=crop&w=900&q=80',
    tags: ['floral', 'powdery', 'aldehydic', 'elegant'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 7200, stock: 5 }],
  },
  {
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    description: 'عطر نسائي شيك جدًا، حمضي زهري مع قاعدة ناعمة، مناسب للخروجات والمناسبات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'floral', 'patchouli', 'elegant'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 7600, stock: 6 }],
  },
  {
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    description: 'عطر نسائي حلو ودافئ بطابع جاذب، مشهور جدًا ومناسب لفصل الشتاء.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=80',
    tags: ['sweet', 'vanilla', 'iris', 'fruity'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 75, price: 5300, stock: 7 }],
  },
  {
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    description: 'عطر نسائي شرقي فانيللا مع قهوة، مناسب للسهرات والأجواء الباردة.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1616604847462-0f2dfc7d8b6d?auto=format&fit=crop&w=900&q=80',
    tags: ['coffee', 'vanilla', 'sweet', 'warm spicy'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 90, price: 5900, stock: 6 }],
  },
  {
    name: 'Good Girl',
    brand: 'Carolina Herrera',
    description: 'عطر نسائي أنثوي قوي، يجمع بين الحلاوة والدفء، مناسب للحفلات والسهرات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1610115677013-7211b67a0d4c?auto=format&fit=crop&w=900&q=80',
    tags: ['sweet', 'tuberose', 'tonka', 'warm'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 80, price: 6100, stock: 6 }],
  },
  {
    name: 'Libre',
    brand: 'Yves Saint Laurent',
    description: 'عطر نسائي حديث باللافندر والفانيلا وزهر البرتقال، أنيق وعملي جدًا.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=80',
    tags: ['lavender', 'vanilla', 'floral', 'citrus'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 90, price: 5200, stock: 7 }],
  },
  {
    name: 'My Way',
    brand: 'Giorgio Armani',
    description: 'عطر نسائي زهري أبيض ناعم، مناسب للنهار والخروجات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&w=900&q=80',
    tags: ['white floral', 'tuberose', 'vanilla', 'fresh'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 90, price: 5000, stock: 6 }],
  },
  {
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    description: 'عطر نسائي منعش جدًا، مثالي للصيف والنهار.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'fresh', 'green', 'summer'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 3900, stock: 8 }],
  },
  {
    name: 'Miss Dior Blooming Bouquet',
    brand: 'Dior',
    description: 'عطر نسائي زهري رقيق وأنثوي، مناسب للنهار والخروجات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1615634262417-4e3f2a39c6f4?auto=format&fit=crop&w=900&q=80',
    tags: ['floral', 'rose', 'fresh', 'soft'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5700, stock: 5 }],
  },
  {
    name: 'J’adore',
    brand: 'Dior',
    description: 'عطر نسائي زهري فاخر وكلاسيكي، مناسب للمناسبات الرسمية.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=80',
    tags: ['white floral', 'elegant', 'fruity', 'luxury'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 6800, stock: 5 }],
  },
  {
    name: 'Burberry Her',
    brand: 'Burberry',
    description: 'عطر نسائي فاكهي سكري عصري، محبب للبنات والشباب.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=80',
    tags: ['fruity', 'sweet', 'berries', 'musky'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 4900, stock: 7 }],
  },
  {
    name: 'Flowerbomb',
    brand: 'Viktor & Rolf',
    description: 'عطر نسائي زهري حلو غني، مناسب للمساء والسهرات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1616604847462-0f2dfc7d8b6d?auto=format&fit=crop&w=900&q=80',
    tags: ['floral', 'sweet', 'patchouli', 'warm'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 5600, stock: 5 }],
  },
  {
    name: 'Alien',
    brand: 'Mugler',
    description: 'عطر نسائي مميز وفواح بطابع ياسمين وعنبر أبيض.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1610115677013-7211b67a0d4c?auto=format&fit=crop&w=900&q=80',
    tags: ['white floral', 'amber', 'jasmine', 'bold'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 90, price: 5400, stock: 4 }],
  },
  {
    name: 'Scandal',
    brand: 'Jean Paul Gaultier',
    description: 'عطر نسائي عسلي زهري قوي وملفت، مناسب للسهرات.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=80',
    tags: ['honey', 'sweet', 'white floral', 'bold'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 80, price: 5000, stock: 6 }],
  },
  {
    name: 'Mon Guerlain',
    brand: 'Guerlain',
    description: 'عطر نسائي أنيق بلافندر وفانيلا، ناعم وفخم.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&w=900&q=80',
    tags: ['lavender', 'vanilla', 'powdery', 'soft'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 6100, stock: 4 }],
  },
  {
    name: 'Twilly d’Hermès',
    brand: 'Hermès',
    description: 'عطر نسائي به توابل خفيفة وزنجبيل وزهور، مختلف وأنيق.',
    category: 'women',
    imageUrl: 'https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?auto=format&fit=crop&w=900&q=80',
    tags: ['ginger', 'floral', 'warm spicy', 'tuberose'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 85, price: 5800, stock: 4 }],
  },

  {
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    description: 'عطر يونيكس فاخر جدًا بطابع سكري خشبي وعنبر، مشهور وثباته ممتاز.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=900&q=80',
    tags: ['amber', 'saffron', 'woody', 'sweet'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 70, price: 14500, stock: 3 }],
  },
  {
    name: 'Ombre Nomade',
    brand: 'Louis Vuitton',
    description: 'عطر يونيكس عودي فاخر قوي جدًا، مناسب لمحبي الروائح الثقيلة والشرقية.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=80',
    tags: ['oud', 'rose', 'amber', 'smoky'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 13800, stock: 3 }],
  },
  {
    name: 'Tobacco Vanille',
    brand: 'Tom Ford',
    description: 'عطر يونيكس تبغ وفانيلا دافئ وفخم، مثالي لفصل الشتاء والمناسبات.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=900&q=80',
    tags: ['tobacco', 'vanilla', 'warm spicy', 'sweet'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 11900, stock: 4 }],
  },
  {
    name: 'Oud Satin Mood',
    brand: 'Maison Francis Kurkdjian',
    description: 'عطر يونيكس فاخر بورد وعود وفانيلا، ناعم وثقيل في نفس الوقت.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?auto=format&fit=crop&w=900&q=80',
    tags: ['oud', 'rose', 'vanilla', 'oriental'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 70, price: 13200, stock: 3 }],
  },
  {
    name: 'CK One',
    brand: 'Calvin Klein',
    description: 'عطر يونيكس منعش وخفيف، مناسب للاستخدام اليومي والسن الصغير.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'green', 'fresh', 'light'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 2600, stock: 10 }],
  },
  {
    name: 'Santal 33',
    brand: 'Le Labo',
    description: 'عطر يونيكس خشبي جلدي ناعم، مميز جدًا وله طابع فخم.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?auto=format&fit=crop&w=900&q=80',
    tags: ['sandalwood', 'leather', 'woody', 'musky'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 10800, stock: 4 }],
  },
  {
    name: 'Molecule 01',
    brand: 'Escentric Molecules',
    description: 'عطر يونيكس نظيف جدًا وخفيف، مناسب للتراكيب والروائح الهادية.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=80',
    tags: ['musky', 'clean', 'minimal', 'woody'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 6200, stock: 5 }],
  },
  {
    name: 'Gypsy Water',
    brand: 'Byredo',
    description: 'عطر يونيكس حمضي خشبي ناعم، مناسب للنهار والذوق الهادي.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'woody', 'vanilla', 'fresh'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 9800, stock: 4 }],
  },
  {
    name: 'Another 13',
    brand: 'Le Labo',
    description: 'عطر يونيكس مسكي أمبروكسان نظيف، بسيط وفاخر.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?auto=format&fit=crop&w=900&q=80',
    tags: ['ambroxan', 'musky', 'clean', 'skin scent'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 11000, stock: 3 }],
  },
  {
    name: 'Musc Ravageur',
    brand: 'Frederic Malle',
    description: 'عطر يونيكس مسكي دافئ وحسي، مناسب للمساء.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1615368144592-9d34d34f0f4b?auto=format&fit=crop&w=900&q=80',
    tags: ['musky', 'amber', 'vanilla', 'warm'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 12500, stock: 2 }],
  },
  {
    name: 'Wood Sage & Sea Salt',
    brand: 'Jo Malone',
    description: 'عطر يونيكس بحري منعش وخفيف، مناسب للنهار والصيف.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?auto=format&fit=crop&w=900&q=80',
    tags: ['marine', 'salty', 'woody', 'fresh'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 6700, stock: 5 }],
  },
  {
    name: 'Neroli Portofino',
    brand: 'Tom Ford',
    description: 'عطر يونيكس حمضي منعش وفاخر، مناسب جدًا للأجواء الصيفية.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1610461888750-10bfc601b874?auto=format&fit=crop&w=900&q=80',
    tags: ['neroli', 'citrus', 'fresh', 'white floral'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 9700, stock: 4 }],
  },
  {
    name: 'Aventus Cologne',
    brand: 'Creed',
    description: 'عطر يونيكس منعش وأنيق بلمسة حمضية وخشبية راقية.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?auto=format&fit=crop&w=900&q=80',
    tags: ['citrus', 'woody', 'fresh', 'ginger'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 13900, stock: 3 }],
  },
  {
    name: 'L’Immensité',
    brand: 'Louis Vuitton',
    description: 'عطر يونيكس زنجبيل حمضي نظيف وفاخر، مناسب للاستخدام اليومي.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=80',
    tags: ['ginger', 'citrus', 'amber', 'fresh'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 13600, stock: 3 }],
  },
  {
    name: 'Imagination',
    brand: 'Louis Vuitton',
    description: 'عطر يونيكس منعش وأنيق بطابع شاي حمضي فاخر.',
    category: 'unisex',
    imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=900&q=80',
    tags: ['tea', 'citrus', 'amber', 'clean'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 14200, stock: 3 }],
  },

  {
    name: 'Naxos',
    brand: 'Xerjoff',
    description: 'عطر نييش بالعسل والتبغ واللافندر، فخم وثابت جدًا ومميز.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615368144592-9d34d34f0f4b?auto=format&fit=crop&w=900&q=80',
    tags: ['honey', 'tobacco', 'lavender', 'sweet'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 9800, stock: 4 }],
  },
  {
    name: 'Layton',
    brand: 'Parfums de Marly',
    description: 'عطر نييش بالتفاح والفانيلا والبهارات، جذاب جدًا وسهل اللبس.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=80',
    tags: ['apple', 'vanilla', 'spicy', 'woody'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 125, price: 10400, stock: 4 }],
  },
  {
    name: 'Erba Pura',
    brand: 'Xerjoff',
    description: 'عطر نييش فاكهي سكري قوي وفواح، مناسب لمحبي الروائح الملفتة.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?auto=format&fit=crop&w=900&q=80',
    tags: ['fruity', 'sweet', 'musky', 'citrus'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 9300, stock: 5 }],
  },
  {
    name: 'Herod',
    brand: 'Parfums de Marly',
    description: 'عطر نييش تبغي قرفي دافئ، مناسب للشتاء والمساء.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=80',
    tags: ['tobacco', 'cinnamon', 'vanilla', 'woody'],
    featured: false,
    bestseller: true,
    sizes: [{ sizeMl: 125, price: 10900, stock: 3 }],
  },
  {
    name: 'Carlisle',
    brand: 'Parfums de Marly',
    description: 'عطر نييش شرقي فاخر بحلاوة أنيقة وثبات قوي.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615368144592-9d34d34f0f4b?auto=format&fit=crop&w=900&q=80',
    tags: ['sweet', 'nutmeg', 'vanilla', 'patchouli'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 125, price: 11200, stock: 3 }],
  },
  {
    name: 'Alexandria II',
    brand: 'Xerjoff',
    description: 'عطر نييش فاخر عودي بودري ناعم جدًا وثقيل.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?auto=format&fit=crop&w=900&q=80',
    tags: ['oud', 'powdery', 'woody', 'amber'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 14800, stock: 2 }],
  },
  {
    name: 'Reflection Man',
    brand: 'Amouage',
    description: 'عطر نييش رجالي أبيض زهري أنيق ونظيف جدًا.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
    tags: ['white floral', 'woody', 'clean', 'luxury'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 12500, stock: 3 }],
  },
  {
    name: 'Interlude Man',
    brand: 'Amouage',
    description: 'عطر نييش دخاني راتنجي قوي جدًا، لمحبي الروائح الثقيلة.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1619994403073-2cec1df8cc6e?auto=format&fit=crop&w=900&q=80',
    tags: ['smoky', 'resinous', 'amber', 'oud'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 12900, stock: 2 }],
  },
  {
    name: 'Side Effect',
    brand: 'Initio',
    description: 'عطر نييش دافئ جذاب بالرم والفانيلا، مناسب للمساء.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80',
    tags: ['rum', 'vanilla', 'tobacco', 'cinnamon'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 90, price: 11800, stock: 3 }],
  },
  {
    name: 'Rehab',
    brand: 'Initio',
    description: 'عطر نييش ناعم وفاخر بطابع خشبي مسكي مريح.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=900&q=80',
    tags: ['lavender', 'sandalwood', 'musky', 'woody'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 90, price: 11600, stock: 3 }],
  },
  {
    name: 'Atomic Rose',
    brand: 'Initio',
    description: 'عطر نييش وردي قوي وفخم، مناسب لمحبي الورود الجريئة.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=900&q=80',
    tags: ['rose', 'vanilla', 'amber', 'bold'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 90, price: 11400, stock: 3 }],
  },
  {
    name: 'Oajan',
    brand: 'Parfums de Marly',
    description: 'عطر نييش سكري دافئ بالقرفة والعسل، ممتاز للبرد.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=80',
    tags: ['honey', 'cinnamon', 'vanilla', 'amber'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 125, price: 10800, stock: 3 }],
  },
  {
    name: 'Ani',
    brand: 'Nishane',
    description: 'عطر نييش فانيلا راقية بلمسة حمضية وبهارات، محبوب جدًا.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615529328331-f8917597711f?auto=format&fit=crop&w=900&q=80',
    tags: ['vanilla', 'ginger', 'green', 'sweet'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 9800, stock: 4 }],
  },
  {
    name: 'Hacivat',
    brand: 'Nishane',
    description: 'عطر نييش حمضي أناناس وخشب، مناسب لمحبي الروائح الفخمة المنعشة.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1615368144592-9d34d34f0f4b?auto=format&fit=crop&w=900&q=80',
    tags: ['pineapple', 'citrus', 'woody', 'oakmoss'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 100, price: 9900, stock: 4 }],
  },
  {
    name: 'Portrait of a Lady',
    brand: 'Frederic Malle',
    description: 'عطر نييش وردي بخوري فاخر جدًا وثقيل.',
    category: 'niche',
    imageUrl: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=900&q=80',
    tags: ['rose', 'incense', 'patchouli', 'berry'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 100, price: 13100, stock: 2 }],
  },

  {
    name: 'Travel Discovery Set',
    brand: 'Velnor House',
    description: 'مجموعة هدايا صغيرة من 4 روائح مختارة، مناسبة للتجربة أو الإهداء.',
    category: 'gift-sets',
    imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=80',
    tags: ['gift set', 'miniatures', 'travel', 'discovery'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 20, price: 2200, stock: 12 }],
  },
  {
    name: 'Luxury Women Gift Box',
    brand: 'Velnor House',
    description: 'بوكس نسائي فاخر يضم 3 روائح مختارة بعناية، مناسب للهدايا.',
    category: 'gift-sets',
    imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=80',
    tags: ['gift set', 'women', 'luxury', 'box'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 30, price: 3600, stock: 10 }],
  },
  {
    name: 'Luxury Men Gift Box',
    brand: 'Velnor House',
    description: 'بوكس رجالي أنيق يضم 3 عطور مختارة، مناسب للهدايا والمناسبات.',
    category: 'gift-sets',
    imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=80',
    tags: ['gift set', 'men', 'luxury', 'box'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 30, price: 3600, stock: 10 }],
  },
  {
    name: 'Couples Perfume Set',
    brand: 'Velnor House',
    description: 'بوكس هدايا مزدوج يضم عطرين متناسقين للرجال والنساء.',
    category: 'gift-sets',
    imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=80',
    tags: ['gift set', 'couple', 'romantic', 'box'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 50, price: 4200, stock: 8 }],
  },
  {
    name: 'Niche Discovery Collection',
    brand: 'Velnor House',
    description: 'مجموعة تجريبية تضم 5 روائح نييش مميزة لعشاق العطور الفاخرة.',
    category: 'gift-sets',
    imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=80',
    tags: ['gift set', 'niche', 'discovery', 'samples'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 10, price: 2800, stock: 9 }],
  },
];

const bagData = [
  {
    type: 'bag',
    name: 'Birkin 25 Gold',
    brand: 'Hermès',
    description: 'The epitome of luxury. Crafted from Togo leather with gold-plated hardware. A timeless investment piece.',
    category: 'bag',
    imageUrl: 'https://images.unsplash.com/photo-1584917033904-491a84b2ebf7?auto=format&fit=crop&w=900&q=80',
    tags: ['luxury', 'leather', 'handbag', 'iconic'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 0, price: 850000, stock: 1 }],
    metadata: { material: 'Togo Leather', color: 'Gold', size: '25cm' }
  },
  {
    type: 'bag',
    name: 'Classic Flap Bag',
    brand: 'Chanel',
    description: 'Signature quilted lambskin leather with silver-tone hardware. The ultimate Parisian chic accessory.',
    category: 'bag',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80',
    tags: ['luxury', 'quilted', 'shoulder bag', 'classic'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 0, price: 420000, stock: 2 }],
    metadata: { material: 'Lambskin', color: 'Black', size: 'Medium' }
  },
  {
    type: 'bag',
    name: 'Lady Dior My ABCDior',
    brand: 'Dior',
    description: 'Cannage lambskin leather with customizable strap. An elegant statement of femininity.',
    category: 'bag',
    imageUrl: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=900&q=80',
    tags: ['luxury', 'cannage', 'dior', 'pink'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 0, price: 285000, stock: 3 }],
    metadata: { material: 'Lambskin', color: 'Cloud Blue', size: 'Small' }
  }
];

const watchData = [
  {
    type: 'watch',
    name: 'Submariner Date',
    brand: 'Rolex',
    description: 'The benchmark for divers\' watches. Oystersteel with Cerachrom bezel and black dial.',
    category: 'watch',
    imageUrl: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=900&q=80',
    tags: ['luxury', 'diver', 'steel', 'automatic'],
    featured: true,
    bestseller: true,
    sizes: [{ sizeMl: 0, price: 720000, stock: 2 }],
    metadata: { movement: 'Automatic', strapMaterial: 'Oystersteel', caseSize: '41mm', color: 'Black' }
  },
  {
    type: 'watch',
    name: 'Nautilus 5711/1A',
    brand: 'Patek Philippe',
    description: 'The most sought-after sports watch in the world. Elegant design inspired by a ship\'s porthole.',
    category: 'watch',
    imageUrl: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=900&q=80',
    tags: ['ultra-luxury', 'sports', 'integrated bracelet'],
    featured: true,
    bestseller: false,
    sizes: [{ sizeMl: 0, price: 4500000, stock: 1 }],
    metadata: { movement: 'Self-winding', strapMaterial: 'Steel', caseSize: '40mm', color: 'Blue' }
  },
  {
    type: 'watch',
    name: 'Tank Louis Cartier',
    brand: 'Cartier',
    description: 'The watch of choice for royalty and icons. 18K rose gold with a beaded crown and sapphire cabochon.',
    category: 'watch',
    imageUrl: 'https://images.unsplash.com/photo-1524592091214-8c97af7c40a7?auto=format&fit=crop&w=900&q=80',
    tags: ['luxury', 'dress watch', 'gold', 'timeless'],
    featured: false,
    bestseller: false,
    sizes: [{ sizeMl: 0, price: 540000, stock: 2 }],
    metadata: { movement: 'Manual Winding', strapMaterial: 'Alligator Leather', caseSize: 'Large', color: 'Rose Gold' }
  }
];

export async function seedPerfumes() {
  const perfumeRepo = AppDataSource.getRepository(Perfume);

  // Seed Perfumes
  const perfumeCount = await perfumeRepo.count({ where: { type: 'perfume' } });
  if (perfumeCount === 0) {
    console.log('Seeding perfumes...');
    const perfumes = perfumeRepo.create(
      perfumeData.map((p) => ({ ...p, type: 'perfume', currency: 'EGP' }))
    );
    await perfumeRepo.save(perfumes);
  } else {
    console.log('Perfumes already exist. Skipping perfume seed.');
  }

  // Seed Bags
  const bagCount = await perfumeRepo.count({ where: { type: 'bag' } });
  if (bagCount === 0) {
    console.log('Seeding bags...');
    const bags = perfumeRepo.create(
      bagData.map((b) => ({ ...b, currency: 'EGP' }))
    );
    await perfumeRepo.save(bags);
  } else {
    console.log('Bags already exist. Skipping bag seed.');
  }

  // Seed Watches
  const watchCount = await perfumeRepo.count({ where: { type: 'watch' } });
  if (watchCount === 0) {
    console.log('Seeding watches...');
    const watches = perfumeRepo.create(
      watchData.map((w) => ({ ...w, currency: 'EGP' }))
    );
    await perfumeRepo.save(watches);
  } else {
    console.log('Watches already exist. Skipping watch seed.');
  }

  console.log('Seeding process completed.');
}